### ISSUE TITLE
z.test returning NA's

### ISSUE THREAD

**Issue by gdunster** [alanarnholt/BSDA#25]
Hello,

I am using the z.test function from the BSDA package in an attempt to analyze some data and I keep getting an output of "NA". There are no errors when I run the test, but all of my outputs ( z=, p-value =, etc) simply say NA. Below is the code I have written to run the analysis, hopefully you can provide some insight.

Dat1 <- Dat[Dat$Year == 1,]
Dat2 <- Dat[Dat$Year == 2,]

sd16 <- sd(Dat1$ColumnA, na.rm = T)
sd17 <- sd(Dat2$ColumnA, na.rm = T)

z.test(x = Dat1$ColumnA, sigma.x = sd16, y = Dat2$ColumnA, sigma.y = sd17)

**Comment by alanarnholt** [comment]
The function does not automatically remove NA values.  I do not have your data but I suspect you have NA values in one or both of Dat1$ColumnA and Dat2$ColumnA.  Try 

`
Dat1 <- Dat[Dat$Year == 1,]
Dat2 <- Dat[Dat$Year == 2,]

sd16 <- sd(Dat1$ColumnA, na.rm = T)
sd17 <- sd(Dat2$ColumnA, na.rm = T)

z.test(x = na.omit(Dat1$ColumnA), sigma.x = sd16, y = na.omit(Dat2$ColumnA), sigma.y = sd17)
`
let me know if that solves your problem.  I will try to write some code in the future to do this automatically.

**Comment by alanarnholt** [comment]
Thanks for bringing this to my attention.  I just updated the code to remove the NAs as I claimed in the documentation.  Please use the development version 1.2.1 for the latest fix.  I will update BSDA on CRAN in a month or so.  Let me know if the code in 1.2.1 solves your issue.

**Comment by gdunster** [comment]
It worked perfectly! Thank you so much for your help!

**Comment by alanarnholt** [comment]
Issue closed
